### ISSUE TITLE
prowgen: Allow generating config only

### ISSUE THREAD

**Issue by ReToCode** [openshift-knative/hack#44]
Currently the `Makefile` does call prowgen multiple times, so the long process of `make ci-operator-config jobs` runs multiple times.

We could either:
- Add some flags to first, prepare the git repo, then only generate the new configs and then run the generation + push only once
- Modify prowgen that it can handle a list of configs and do this loop in code

Other ideas?

**Comment by pierDipi** [comment]
We should try to not run it locally at all: https://github.com/openshift-knative/hack/issues/51
